exclude: src/reportWebVitals.js
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: detect-private-key
          - id: requirements-txt-fixer
    # - repo: https://github.com/pre-commit/mirrors-csslint
    #   rev: v1.0.5
    #   hooks:
    #       - id: csslint
    - repo: https://github.com/pre-commit/mirrors-fixmyjs
      rev: v2.0.0
      hooks:
          - id: fixmyjs
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v2.1.0
      hooks:
          - id: prettier
    # - repo: https://github.com/pre-commit/mirrors-eslint
    #   rev: v9.1.1
    #   hooks:
    #       - id: eslint
    #         files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
    #         types: [file]
